# Generated by Django 4.2 on 2023-04-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_case_qr_code_alter_device_qr_code"),
        ("rental", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rental",
            old_name="equipment",
            new_name="cases",
        ),
        migrations.AddField(
            model_name="rental",
            name="devices",
            field=models.ManyToManyField(to="inventory.device"),
        ),
    ]
