# Generated by Django 4.2 on 2023-04-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="images/cases/"),
        ),
        migrations.AlterField(
            model_name="device",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="images/devices/"),
        ),
    ]
