# Generated by Django 4.2 on 2023-04-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_case_qr_code_alter_device_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="contains",
            field=models.JSONField(default=[]),
        ),
    ]
