# Generated by Django 4.2 on 2023-04-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_case_contains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="contains",
            field=models.JSONField(default=list),
        ),
    ]
